Feat/dualblade
oleneyl/simaple pull request #108
Opened 2022-12-25 13:10 UTC by icepeng

concerns

* 파이널 컷 컴포넌트는 단순히 써든레이드로 인한 쿨감만을 위해 존재하고 있다. 더 일반화해서 처리할 방법이 있지 않을까?
* 히든 블레이드에 있는 지속 시간중 데미지 10% 증가를 위해 TriggableBuffSkill에 stat 멤버와 buff view를 추가했다. default value로 빈 Stat을 넘겨도 괜찮을까?

2022-12-26 03:45 UTC, oleneyl commented
참고로 Event 발생시켰을 때 payload가 콜백 리듀서 payload로 그대로 전달됩니다.

2022-12-31 11:59 UTC, oleneyl requested changes

2022-12-31 11:59 UTC, oleneyl commented on simaple/simulate/component/triggable_buff_skill.py
> +    stat: Stat = Stat()
issue: pydantic.Field(default_factory=Stat)으로 선언해야 합니다.

2022-12-31 11:59 UTC, oleneyl commented on tests/simulate/component/specific/dualblade/conftest.py
> +    return DirectorySpecRepository("simaple/data/skill/resources/components")
question: 이게 왜 또 필요한가요?

2022-12-31 11:59 UTC, oleneyl commented on simaple/simulate/component/specific/dualblade.py
> +        return state, []
nitpick: listening_action할 때 cooldown reducer를 인자를 넘기면서 트리거할수 있게 바꿔야 할 것 같아요. 여기서 할 건 아니고 빠른 시일 내에 피쳐를 추가해야할것같습니다.

2022-12-31 11:59 UTC, oleneyl commented on simaple/simulate/component/specific/dualblade.py
> +        return state, []
이거 하나때문에 컴포넌트 하나가 추가되는게 너무 별로네요.

2022-12-31 11:59 UTC, oleneyl commented on simaple/simulate/component/specific/dualblade.py
> +        return state, events
question: 그냥 keydown trait use랑 다른 이유가 뭔가요?

2022-12-31 12:19 UTC, icepeng commented on simaple/simulate/component/specific/dualblade.py
> +        return state, events
개시 데미지가 따로 있습니다. 인게임 데이터에도 따로 들어가있어요.

2022-12-31 12:29 UTC, oleneyl approved these changes

2022-12-31 12:31 UTC, merged