feat: handle keydown
oleneyl/simaple pull request #114
Opened 2022-12-27 13:17 UTC by icepeng

2022-12-30 04:09 UTC, oleneyl requested changes

2022-12-30 04:09 UTC, oleneyl commented on tests/simulate/component/test_keydown_entity.py
> +
issue: 앞에서도 언급했듯 이렇게 구현한 의도가 궁금합니다. 의도를 알아야 코드 이해가 가능할 것 같아요.

2022-12-30 06:49 UTC, icepeng commented on tests/simulate/component/test_keydown_component.py
> +    print(use_events)
elapse 이후 DELAY 이벤트가 발생하는게 아닌, elapse가 진행되는 동안 어떻게 딜레이 및 데미지 이벤트가 발생해왔는지 보고하는 관점입니다. 예를 들어, 얼티밋 드라이브의 공격마다 콜백이 발생하는 느와르 카르트는 어떻게 들어가야 하는가?를 생각했을때 필요한 정보라고 생각했어요. 결론적으로 시뮬레이션 과정에서 발생한 딜레이의 총합이 실제로 캐릭터에 걸려있던 딜레이 시간과 같아야 한다고 생각했어요.

액터같은 경우에는 현재
use() -> [prepare_delay]
elapse(prepare_delay) -> [delay]
elapse(delay) -> [delay]
...
elapse(delay) -> [keydown_end_delay]

와 같이 동작하고 있는데, 우연히 끼워맞춰진 감이 있네요. 액터 구현도 변경해두겠습니다.

2022-12-30 07:36 UTC, oleneyl commented on tests/simulate/component/test_keydown_component.py
> +    print(use_events)
넹 액터 변경되면 이슈없을듯하네요. 이거  Tag.DELAY 명세를 reserved_names.Tag docstring에 추가해주실수 있나요?

2022-12-30 14:01 UTC, icepeng commented on tests/simulate/component/test_keydown_entity.py
> +
기존 방식으로 돌려놓았습니다.

2022-12-30 14:02 UTC, icepeng commented on tests/simulate/component/test_keydown_component.py
> +    print(use_events)
딜레이 정의를 기존 정의를 유지하도록 돌려놓았습니다.

2022-12-30 14:50 UTC, oleneyl requested changes
question: 근데 예상dpm은 왜 낮아진거에요?

2022-12-30 14:50 UTC, oleneyl commented on simaple/simulate/actor.py
> +        return None
suggestion: 외부에 노출되지 않는 메서드는 퍼블릭 메서드 아래에 선언되면 좋을것 같습니다.

2022-12-30 14:50 UTC, oleneyl commented on simaple/simulate/actor.py
> +            raise ValueError("Running keydown cannot be more than 1")
nitpick: 언젠가 액터 에러를 하나 만들어야할듯하네요. 지금 하실필욘 없습니다.

2022-12-30 14:50 UTC, oleneyl commented on simaple/simulate/component/entity.py
> +        # pylint:disable=chained-comparison
question: 이건 왜 있는건가요?

2022-12-30 14:50 UTC, oleneyl commented on simaple/simulate/component/entity.py
> +            yield 1
suggestion: 이거 값 안쓰면 그냥 yield만 해도 될것같아요

2022-12-30 14:50 UTC, oleneyl commented on simaple/simulate/component/trait/impl.py
> +        ) = self._get_keydown_end_damage_hit_delay()
suggestion: finish_*는 keydown_end 시점에만 가져와도 될 것 같습니다.

2022-12-30 14:50 UTC, oleneyl commented on simaple/simulate/component/trait/impl.py
> +        )
question: 이거 keydown_end 반환하는거 별로같은데, state.is_keydown_end() 메서드로 빼면 문제가 있을까요?

2022-12-30 14:51 UTC, icepeng commented on simaple/simulate/component/entity.py
> +        # pylint:disable=chained-comparison
pylint disable 말씀하시는건가요?

2022-12-30 14:53 UTC, icepeng commented on simaple/simulate/component/trait/impl.py
> +        )
원래는 _on_keydown_end(self, state) -> state를 trait에 넣으려 했는데, Generic을 인식시킬수가 없더라고요. state 안에 상태값이 가능한 적었으면 좋겠어요. 더군다나 지속성이 있다기 보다는 딱 한번 터지고 마는거라서요.

2022-12-30 14:56 UTC, icepeng commented
> question: 근데 예상dpm은 왜 낮아진거에요?
- 스킬 데이터에 prepare_delay가 추가되어서, 그만큼 타격 횟수가 감소했습니다.
- 기존 use에서 keydown_end가 감지될 시 delayed 이벤트가 2개가 발생하는데, AlwaysDelayedActor 구현이 처음 만나는 delay를 집어서 elapse하는 방식이라 keydown_end_delay가 씹히고 있었을거에요.
@oleneyl

2022-12-30 14:58 UTC, icepeng commented on simaple/simulate/component/entity.py
> +        # pylint:disable=chained-comparison
pylint disable 말씀하시는게 맞다면 
`resolving_time_left >= 0 >= self.interval_counter` 으로 쓰는걸 권장하고 있는데, 의미상 이런 느낌의 비교문으로 생각되지 않았어요.

2022-12-30 15:23 UTC, oleneyl commented on simaple/simulate/component/trait/impl.py
> +        )
state의 메서드 아니에요? 상태값이 아니라 기존 값으로부터 도출될 수 있는 프로퍼티인것 같아요.

2022-12-30 18:54 UTC, icepeng commented on simaple/simulate/component/trait/impl.py
> +        )
keydown_end 이벤트를 추가하고, is_keydown_ended를 검사하는 것으로 변경했습니다.

2022-12-31 07:34 UTC, oleneyl approved these changes
LGTM

2022-12-31 07:34 UTC, oleneyl commented on simaple/simulate/component/util.py
> +    return any(event.tag == Tag.KEYDOWN_END for event in events)
nitpick: 슬슬 event tag 관련 메서드를 한 번 정리해야겠네요..

2022-12-31 07:36 UTC, merged