docs: add tutorial
oleneyl/simaple pull request #119
Opened 2022-12-30 06:18 UTC by oleneyl

시뮬레이션 계산과정에 대한 튜토리얼을 작성합니다.

2022-12-30 14:23 UTC, icepeng commented on docs/modules/simulate.rst
> +Reducer는 아래와 같은 sugnature를 가지는 함수입니다.
```suggestion
Reducer는 아래와 같은 signature를 가지는 함수입니다.
```
typo

2022-12-30 14:31 UTC, icepeng requested changes
suggstion: Getting Started에 installation 파트가 있었으면 좋겠어요.

2022-12-30 14:31 UTC, icepeng commented on docs/modules/tutorial/tutorial.rst
> +  - ``character_stat`` : 이 값은 대상 캐릭터의 스텟입니다.
issue: bullet 포매팅이 깨져있습니다.

2022-12-30 14:31 UTC, icepeng commented on docs/modules/tutorial/tutorial.rst
> +이 두가지를 한 번 기록해 보겠습니다. 위 코드를 아래 코드르 대체해 주세요.
```suggestion
이 두가지를 한 번 기록해 보겠습니다. 위 코드를 아래 코드로 대체해 주세요.
```
typo

2022-12-30 14:31 UTC, icepeng commented on docs/modules/simulate.rst
> +스킬의 상태와 스킬에 속하는 리듀서들이 강하게 결합되어, 일종의 클러스터를 형성한다는 사실을 리마인드하십시오.
question: View에 관한 설명은 일부러 제외하신건가요?

2022-12-31 13:07 UTC, oleneyl commented on docs/modules/simulate.rst
> +스킬의 상태와 스킬에 속하는 리듀서들이 강하게 결합되어, 일종의 클러스터를 형성한다는 사실을 리마인드하십시오.
넣을게요. 넣어야할것같아요.

2022-12-31 13:08 UTC, oleneyl commented on docs/modules/simulate.rst
> +스킬의 상태와 스킬에 속하는 리듀서들이 강하게 결합되어, 일종의 클러스터를 형성한다는 사실을 리마인드하십시오.
별도 문서가 필요할 것 같아요. reducer/view에 대한?

2022-12-31 13:54 UTC, icepeng requested changes

2022-12-31 13:54 UTC, icepeng commented on docs/index.rst
> +simaple은 python을 작성된, 메이플스토리 내 최적화와 시뮬레이션을 지원하는 파이썬 라이브러리 입니다.
```suggestion
simaple은 python으로 작성된, 메이플스토리 내 최적화와 시뮬레이션을 지원하는 파이썬 라이브러리 입니다.
```
typo?

2022-12-31 14:27 UTC, icepeng approved these changes

2022-12-31 14:35 UTC, merged