feat: implement hyperstat parser
oleneyl/simaple pull request #68
Opened 2022-12-12 09:01 UTC by jj9810

하이퍼스탯 Parser 구현입니다.

Example:
```
"hyperstat": {
            "STR": 0,
            "DEX": 0,
            "INT": 150.0,
            "LUK": 60.0,
            "HP": 0,
            "MP": 0,
            "DF": 0,
            "PP": 0,
            "critical_rate": 13.0,
            "critical_damage": 12.0,
            "ignored_defence": 36.0,
            "damage_multiplier": 36.0,
            "boss_damage_multiplier": 43.0,
            "immunity": 0,
            "attack_power": 18.0,
            "magic_attack": 18.0,
            "arcaneforce": 0
        },
```

2022-12-12 15:56 UTC, Lechros commented
"HP"->"MHP", "MP"->"MMP"?

2022-12-13 03:11 UTC, oleneyl requested changes

2022-12-13 03:11 UTC, oleneyl commented on simaple/fetch/element/character/extractor.py
> +
suggestion: just regexes.keys() ?

2022-12-13 03:11 UTC, oleneyl commented on simaple/fetch/element/character/extractor.py
> +            "LUK": re.compile("운 \\d+ 증가"),
issue: 스텟퍼 미적용 스텟은 XXX_static 입니다.

2022-12-13 03:11 UTC, oleneyl commented on simaple/fetch/element/character/extractor.py
> +            "MP": re.compile("최대 MP \\d+% 증가"),
issue: MHP, MMP여야 합니다.

2022-12-13 10:39 UTC, oleneyl approved these changes

2022-12-13 10:39 UTC, merged