feat: implement ability parser
oleneyl/simaple pull request #71
Opened 2022-12-15 19:12 UTC by jj9810

기본적인 파서 기능은 제대로 작동하지만 특수 능력치들에 대해 명칭 조율이 필요해보입니다.

2022-12-18 06:31 UTC, oleneyl requested changes

2022-12-18 06:31 UTC, oleneyl commented on simaple/fetch/element/character/extractor.py
> +            # 메소 획득량 \\d+% 증가
suggestion: r"" 사용하는건 어때요? `r'다수 공격 스킬의 공격 대상 \d+ 증가'`

2022-12-20 04:41 UTC, jj9810 commented on simaple/fetch/element/character/extractor.py
> +            # 메소 획득량 \\d+% 증가
수정완료

2022-12-20 10:50 UTC, oleneyl approved these changes

2022-12-20 10:50 UTC, merged