Adele (WIP)
oleneyl/simaple pull request #92
Opened 2022-12-22 17:25 UTC by icepeng

2022-12-24 03:08 UTC, icepeng commented on simaple/core/base.py
> +    def stack(self, stack: int) -> Stat:
StackableBuffSkill을 위한 메소드로, armor_ignore 및 final_damage_multiplier를 단순 합산합니다.

2022-12-24 03:10 UTC, icepeng commented on simaple/data/passive_hyper_skill/resources/adele.yaml
> +  target: 에테르
레조넌스 - 엑스트라 힐링을 에테르에 지정된 stack_per_resonance를 patch하는 방식으로 구현합니다.

2022-12-24 03:25 UTC, icepeng commented on simaple/simulate/component/state.py
> +    def set_time_left(self, time: float, initial_counter: Optional[float] = None):
첫 tick 발생까지의 시점을 제어할 수 있도록 initial_counter를 추가합니다.

2022-12-24 04:15 UTC, icepeng commented on simaple/simulate/component/trait/impl.py
> +        hit_multiplier=1,
메카닉 로봇 마스터리로 추가되는 duration_multiplier와 마찬가지로, hit_multiplier를 추가합니다.

2022-12-24 07:03 UTC, oleneyl requested changes

2022-12-24 07:03 UTC, oleneyl commented on simaple/simulate/component/specific/adele.py
> +    def get_default_state(self):
question(non-blocking): 상태를 상속한 자식 상태에 대해 trait 사용을 허용할지 고민되네요.

2022-12-24 07:03 UTC, oleneyl commented on tests/simulate/component/specific/adele/test_ether.py
> +    ether.resonance(None)  # 100
suggestion: for _ in range(5): ?

2022-12-24 07:03 UTC, oleneyl commented on tests/simulate/component/specific/adele/test_gathering.py
> +        OrderState(interval=1020, running_swords=[(0, 40000), (0, 40000), (0, 40000)]),
question: running_sword 값이 다를 경우에 대한 테스트는 필요 없을까요?

2022-12-24 07:03 UTC, oleneyl commented on tests/simulate/component/specific/adele/test_gathering.py
> +
suggestion: tests/ 안에 util.py였나? 에 dealing event count해주는 유틸리티가 있습니다.

2022-12-24 07:03 UTC, oleneyl commented on tests/simulate/component/specific/mechanic/test_carrier.py
> +        cooldown=200_000,
praise: good

2022-12-24 07:11 UTC, icepeng commented on simaple/simulate/component/trait/impl.py
> +        hit_multiplier=1,
스톰처럼 1개 이벤트에 타수가 늘어나는 경우도 있고, 이벤트가 n회가 되는 경우 둘 다 있어서 고민되네요.

2022-12-24 07:12 UTC, icepeng commented on simaple/simulate/component/view.py
> +    stack: Optional[float] = None
관계성이 높은 멤버끼리 가깝게 위치하려는 목적이에요.

2022-12-24 07:13 UTC, icepeng commented on tests/simulate/component/specific/adele/test_gathering.py
> +        OrderState(interval=1020, running_swords=[(0, 40000), (0, 40000), (0, 40000)]),
running_sword의 time_left 값을 말씀하시는게 맞을까요? 테스트하고자 하는 대상은 running_swords의 length에 따른 타격 횟수이기 때문에 필요없다고 생각해요.

2022-12-24 08:16 UTC, icepeng commented on simaple/simulate/component/skill.py
> +    cooldown: float = 0.0
default cooldown 걸려있는 컴포넌트가 여럿 있는데 (BuffSkillComponent 포함), 전부 제거할까요?

2022-12-24 08:21 UTC, icepeng commented on simaple/simulate/component/skill.py
> +        if duration_state.time_left <= 0:
rejection 검사는 use_durable_trait 안에서 실행되고, 해당 코드는 "스킬이 종료되기 전에 스택을 이어나갔는지, 아니면 종료된 후에 다시 사용했는지"에 대한 검사에요.

2022-12-24 08:51 UTC, icepeng commented on simaple/simulate/component/specific/adele.py
> +    def get_default_state(self):
상태를 reduce하는 메소드를 건드리지 않고, 다른 컴포넌트에 bind할 때 추가적인 정보를 전달하기 위한 목적으로만 상태의 상속을 허용한다면 trait 사용도 허용할 수 있다고 생각해요.

2022-12-24 09:06 UTC, icepeng commented on simaple/simulate/component/specific/adele.py
> +        )
두번째 인자명을 명시하는 것으로 해두었습니다. State를 새로 만드는게 오히려 더 복잡해졌어요.

2022-12-24 09:12 UTC, icepeng commented on simaple/simulate/component/specific/adele.py
> +        return (cooldown_state, dynamics, order_state, ether_state, restore_state), [
DurableTrait은 duration_state를 사용하지 않고 order_state를 사용해서 쓸수 없고, TickEmittingTrait도 마찬가지로 interval_state가 아닌 order_state를 사용하기 때문에... 마땅히 쓸만한 trait이 없었어요.

2022-12-24 11:20 UTC, oleneyl requested changes

2022-12-24 11:20 UTC, oleneyl commented on simaple/simulate/component/specific/adele.py
> +        return (cooldown_state, dynamics, order_state, ether_state, restore_state), [
으음..섞어쓸수도없었나보네요.

2022-12-24 11:20 UTC, oleneyl commented on simaple/simulate/component/specific/adele.py
> +            valid=cooldown_state.available and order_state.get_sword_count() > 0,
issue: is_valid가 valid로 들어가야할것같아요

2022-12-24 11:20 UTC, oleneyl commented on simaple/simulate/component/specific/adele.py
> +    def get_default_state(self):
그럼 여기서 한 번 써보시는건..? 지금 해당 컴포넌트의 리듀서들이 사실 DurableTrait과 동일하잖아요?

2022-12-24 11:20 UTC, oleneyl commented on simaple/simulate/component/trait/impl.py
> +        hit_multiplier=1,
음, 트리거가 여러번 필요한 경우에만 n회로 강제할까요? 규칙을 정해두면 좋을것같네요

2022-12-24 11:20 UTC, oleneyl commented on tests/simulate/component/specific/adele/test_gathering.py
> +        OrderState(interval=1020, running_swords=[(0, 40000), (0, 40000), (0, 40000)]),
네 순차적으로 종료가 잘 되는지에 대한 테스트요

2022-12-24 17:24 UTC, icepeng commented on simaple/simulate/component/specific/adele.py
> +    def get_default_state(self):
cooldown_state가 없어서... 조금 달라요. 리스토어가 쿨다운을 가지고, 리스토어(버프)가 listen하는 방식이라서요.

2022-12-25 03:47 UTC, oleneyl commented on simaple/simulate/component/specific/adele.py
> +    def get_default_state(self):
아하..이해했습니다

2022-12-25 03:49 UTC, oleneyl commented on simaple/simulate/component/skill.py
> +    cooldown: float = 0.0
제거 자체는 이슈로 따두고 지금은 이정도로만..

2022-12-25 03:50 UTC, oleneyl approved these changes

2022-12-25 03:50 UTC, merged